### ISSUE TITLE
The rayon example do not work: total number of jobs is always 0

### ISSUE THREAD

**Issue by simnalamburt** [mitsuhiko/indicatif#195]
The rayon example in the [document](https://docs.rs/indicatif/0.15.0/indicatif/#iterators) do not work anymore. The total number of jobs is always 0.

### How to reproduce
```rust
// src.main.rs
use indicatif::ParallelProgressIterator;
use rayon::iter::{ParallelIterator, IntoParallelRefIterator};

fn main() {
    let v: Vec<_> = (0..100000).collect();
    let v2: Vec<_> = v.par_iter().progress().map(|i| i + 1).collect();
    assert_eq!(v2[0], 1);
}
```
```toml
# Cargo.toml
[package]
name = "indicatif-test"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1.1"
indicatif = {version = "*", features = ["rayon"]}
```

Or download [indicatif-test.tar.gz](https://github.com/mitsuhiko/indicatif/files/5101736/indicatif-test.tar.gz) and run it.

### Expected result
Moving progress bar

### Actual result
Total number of jobs is misguessed as 0.

![image](https://user-images.githubusercontent.com/4435445/90745049-1e41de00-e30b-11ea-96d6-d63882d943a5.png)
